#!/bin/bash

if [ -f .screenrc ]; then
	mv .screenrc .screenrc~
fi
ln -sb dotfiles/.screenrc .

if [ -f .bash_profile ]; then
	mv .bash_profile .bash_profile~
fi
ln -sb dotfiles/.bash_profile .

if [ -f .bashrc ]; then
	mv .bashrc .bashrc~
fi
ln -sb dotfiles/.bashrc .

if [ -f .bashrc_custom ]; then
	mv .bashrc_custom .bashrc_custom~
fi
ln -sb dotfiles/.bashrc_custom .

if [ -d .emacs.d ]; then
	mv .emacs.d .emacs.d~
fi
ln -s dotfiles/.emacs.d .

if [ -f .vimrc ]; then
	mv .vimrc .vimrc~
fi
ln -sb dotfiles/.vimrc .

if [ -f .gitconfig ]; then
	mv .gitconfig .gitconfig~
fi
ln -sb dotfiles/.gitconfig .

